# Default initial positions for robot's ros2_control fake system

initial_positions:
  base_link_to_cube3: 0
  base_link_to_cube3-copy0: 0
  cube3-copy0_to_cube3-copy4: 0
  cube3_to_cube3-copy3: 0
  cylinder3-copy5_to_cylinder3: 0
  cylinder3-copy6_to_cylinder3-copy2: 0
  ee1_pitch_joint: 0
  ee1_roll_joint: 0
  ee1_yaw_joint: 0
  ee2_pitch_joint: 0
  ee2_roll_joint: 0
  ee2_yaw_joint: 0